[tool.black]
line-length = 77 
target-version = ['py38', 'py39', 'py310', 'py311', 'py312',]
include = '\.pyi?$'

[tool.ruff]
line-length = 77 

[tool.ruff.lint]
select = [
    "E", 
    "W", 
    "F", 
    "I",
    "C90", 
    "N", 
    "UP", 
    "B", 
    "A", 
    "C4", 
    "T20",
]

ignore = ["E501", "B008"]

[tool.ruff.lint.isort]
known-first-party = ["fastapi"]
order-by-type = true

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["E402", "F401"]
"migrations/*.py" = ["E501"]
